# Generated by Django 2.2.6 on 2020-01-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('temperature', models.FloatField(max_length=45)),
                ('oxygen', models.FloatField(max_length=45)),
                ('heartRate', models.FloatField(max_length=45)),
                ('breath', models.FloatField(max_length=45)),
            ],
        ),
    ]
