# Generated by Django 2.2.9 on 2020-01-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='oxygen',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
